### ISSUE TITLE
FreeBSD Missing Dependency 

### ISSUE THREAD

**Issue by okalm** [Xanthus58/FileSorterX#15]
Hi there,

`FileSorterX` complains about a missing dependency `libssl.so.11` which is installed by the package `openssl`, it's not installed by default at least in my case. 
Once `openssl` is installed FileSortedX doesn't give any warning and works.

OS: FreeBSD 13.1-RELEASE
Package version: FileSorterX_v1.2.0_x86_64-unknown-freebsd

**Comment by Xanthus58** [comment]
Hey thanks a ton for bringing it to my attention; I don't have any means to actually test freebsd at the moment. But I'll take a look into it and see what I can do for the next patch.

**Comment by Xanthus58** [comment]
Hey, not entirely sure that this is something i can actually fix on my end; at least I've not been able to find any reliable way while testing in a vm. I think users of the application will just have to install openssl; I'll get @WolfenXVII to put a warning/notice about it on the readme
