### ISSUE TITLE
Telemetry is Opt-out

### ISSUE THREAD

**Issue by FlameOrchid** [Xanthus58/FileSorterX#26]
1. Telemetry is enabled by default, which will not be met well in the Linux community.
2. Telemetry collects data that can identify user (e.g. ``input_dir = "/exl_arch/—3—PROJ—3—/eurystheus/src/"`` or ``input_dir = /home/exl/—2—POLY—2—/music/``).

Solution: Make telemetry Opt-in, so when user encounters error they can enable this feature once and submit useful data that way. Also this will not create ton of useless data.

**Comment by Xanthus58** [comment]
Good suggestion that I'll go ahead and roll it out in the next update

**Comment by Xanthus58** [comment]
Fix waiting to be rolled out; thanks for the suggestion. https://github.com/Xanthus58/FileSorterX/commit/f9ad811084f5bf91b878892c396f6a559356f183
